create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_email UNIQUE (email)
);

create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    annotation VARCHAR(250) NOT NULL,
    description VARCHAR(512) NOT NULL,
    event_date TIMESTAMP,
    is_paid BOOLEAN NOT NULL,
    participation_limit INTEGER,
    request_moderation BOOLEAN,
    title VARCHAR(250) NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);