CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL
);

-- Индекс для быстрого поиска опубликованных комментариев события
CREATE INDEX IF NOT EXISTS idx_comments_event_status ON comments(event_id, status);

-- Индекс для подсчета комментариев
CREATE INDEX IF NOT EXISTS idx_comments_event_status_count ON comments(event_id) WHERE status = 'PUBLISHED';