server:
  port: 0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/ewm-category-service}
    username: ${SPRING_DATASOURCE_USERNAME:category}
    password: ${SPRING_DATASOURCE_PASSWORD:category}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 40
      minimum-idle: 10
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    ru.practicum: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2