create TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT,
    created_on TIMESTAMP,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP,
    initiator_id BIGINT,
    lat DECIMAL(10, 8) NOT NULL,
    lon DECIMAL(11, 8) NOT NULL,
    is_paid BOOLEAN NOT NULL,
    participant_Limit INTEGER,
    published_on TIMESTAMP,
    request_moderation BOOLEAN,
    state VARCHAR(20) DEFAULT 'PENDING',
    title VARCHAR(120) NOT NULL,
    views BIGINT DEFAULT 0,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT chk_latitude CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT chk_longitude CHECK (lon BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS idx_location_coords ON events (lat, lon);